[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python server.py"
healthcheckPath = "/"
healthcheckTimeout = 100

[service]
internal_port = 8000

[[headers]]
for = "/api/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "POST, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"